#!/bin/sh
# WebcamStudio for GNU/Linux Launcher wrapper
# Copyright (C) 2008 Patrick Balleux <patrick.balleux@gmail.com>
# Copyright (C) 2013 PhobosK <phobosk@kbfx.net>
# Copyright (C) 2015 Karl Ellis <soylent.tv@gmail.com>
# Version 1.0

INSTALLDIR=/usr/lib/truckliststudio

# Include java-wrappers
. /usr/lib/java-wrappers/java-wrappers.sh

JAVA_CLASSPATH="${INSTALLDIR}/*:${INSTALLDIR}/lib/*"
JAVA_ARGS="-Djna.nosys=true -splash:start.gif"

find_java_runtime openjdk sunmin5

find_jars AppFramework \
  commons-cli \
  commons-codec \
  commons-httpclient \
  commons-lang3 \
  jcl-over-slf4j \
  jsr305 \
  log4j-1.2 \
  netty \
  slf4j-api \
  slf4j-log4j12 \
  swing-worker

cd ${INSTALLDIR}

run_java truckliststudio.TrucklistStudio "$@"
