#!/bin/sh
# WebcamStudio for GNU/Linux Launcher wrapper
# Copyright (C) 2008 Patrick Balleux <patrick.balleux@gmail.com>
# Copyright (C) 2013 PhobosK <phobosk@kbfx.net>
# Copyright (C) 2015 Karl Ellis <soylent.tv@gmail.com>
# Version 1.0

INSTALLDIR=/usr/lib/truckliststudio

# Include java-wrappers
. /usr/lib/java-wrappers/java-wrappers.sh

JAVA_CLASSPATH="${INSTALLDIR}/*:${INSTALLDIR}/lib/*"
JAVA_ARGS="-Djna.nosys=true -splash:start.gif"

cd ${INSTALLDIR}

run_java truckliststudio.TrucklistStudio "$@"
